FROM php:7.0-apache

RUN apt-get update -y
RUN apt-get install -y wget zlib1g-dev libxml2-dev libmemcached-dev

RUN pecl install memcached
RUN docker-php-ext-enable memcached
RUN apt-get clean -y
RUN docker-php-ext-install pdo pdo_mysql mysqli soap

RUN echo ''|pecl install -o -f redis \
&&  rm -rf /tmp/pear \
&&  docker-php-ext-enable redis

RUN cd /root \
    && wget http://downloads.datastax.com/cpp-driver/ubuntu/16.04/dependencies/libuv/v1.11.0/libuv_1.11.0-1_amd64.deb \
    && wget http://downloads.datastax.com/cpp-driver/ubuntu/16.04/dependencies/libuv/v1.11.0/libuv-dev_1.11.0-1_amd64.deb \
    && wget http://downloads.datastax.com/cpp-driver/ubuntu/16.04/cassandra/v2.8.0/cassandra-cpp-driver-dev_2.8.0-1_amd64.deb \
    && wget http://downloads.datastax.com/cpp-driver/ubuntu/16.04/cassandra/v2.8.0/cassandra-cpp-driver_2.8.0-1_amd64.deb \
    && dpkg -i libuv_1.11.0-1_amd64.deb \
    && dpkg -i libuv-dev_1.11.0-1_amd64.deb \
    && wget http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u9_amd64.deb \
    && dpkg -i libssl1.0.0_1.0.1t-1+deb8u9_amd64.deb \
    && dpkg -i cassandra-cpp-driver_2.8.0-1_amd64.deb \
    && dpkg -i cassandra-cpp-driver-dev_2.8.0-1_amd64.deb \
    && apt-get install -y libgmp-dev \
    && pecl install cassandra \
    && echo "extension=cassandra.so" >> /etc/php/7.0/apache2/php.ini \
    && echo "extension=cassandra.so" >> /etc/php/7.0/cli/php.ini

## Set default volume for image
## This would be overrided by docker-compose for updatable source code between development
COPY . /data
WORKDIR /data

COPY .docker/vhost.conf /etc/apache2/sites-available/000-default.conf

RUN sed -i -e 's/${PUBLIC_DIR}//g' /etc/apache2/sites-available/000-default.conf

RUN chown -R www-data:www-data /data \
    && a2enmod rewrite

#
## Fixes user permissions for Mac OS [https://github.com/boot2docker/boot2docker/issues/581]
RUN usermod -u 1000 www-data
RUN usermod -G staff www-data

RUN apache2ctl restart || service apache2 restart
