FROM php:5.6-apache

RUN docker-php-ext-install mysqli

MAINTAINER Paul Redmond

## Set default volume for image
## This would be overrided by docker-compose for updatable source code between development
COPY . /data
WORKDIR /data

COPY .docker/vhost.conf /etc/apache2/sites-available/000-default.conf

RUN sed -i -e 's/${PUBLIC_DIR}/$PUBLIC_DIR/g' /etc/apache2/sites-available/000-default.conf

RUN chown -R www-data:www-data /data \
    && a2enmod rewrite

#
## Fixes user permissions for Mac OS [https://github.com/boot2docker/boot2docker/issues/581]
RUN usermod -u 1000 www-data
RUN usermod -G staff www-data

RUN service apache2 restart
