data:
  image: busybox
  volumes:
    - '.:/data'
    - './mysql-data:/var/lib/mysql'
db:
  image: aimakun/mysql
  restart: always
  command: '--default-authentication-plugin=mysql_native_password'
  ports:
    - '3306'
  environment:
    MYSQL_DATABASE: 2web_web2container4dev_dev
    MYSQL_ROOT_PASSWORD: root
  volumes:
    - /sessions
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  restart: always
  environment:
    PMA_ARBITRARY: '1'
    PMA_PORT: 3306
    PMA_USER: root
    PMA_PASSWORD: root
  links:
    - db
  ports:
    - '8080:80'
  volumes:
    - /sessions
web:
  build: /Users/alex/projects/web2container4dev
  dockerfile: Dockerfile-php7.2
  volumes_from:
    - data
  ports:
    - '80'
  links:
    - db
  environment:
    MYSQL_HOST: db
    SITE_ENV: dev_docker
    VIRTUAL_HOST: web2container4dev.dev.local
    PUBLIC_DIR: /public
  extra_hosts:
    - 'web2container4dev.dev.local:127.0.0.2'
