FROM php:7.2-apache

RUN apt-get update -y
RUN apt-get install -y libxml2-dev libmemcached-dev

RUN pecl install memcached
RUN docker-php-ext-enable memcached
RUN apt-get clean -y
RUN docker-php-ext-install pdo pdo_mysql mysqli soap

RUN echo ''|pecl install -o -f redis \
&&  rm -rf /tmp/pear \
&&  docker-php-ext-enable redis


MAINTAINER Paul Redmond

## Set default volume for image
## This would be overrided by docker-compose for updatable source code between development
COPY . /data
WORKDIR /data

COPY .docker/vhost.conf /etc/apache2/sites-available/000-default.conf

RUN sed -i -e 's/${PUBLIC_DIR}/$PUBLIC_DIR/g' /etc/apache2/sites-available/000-default.conf

RUN chown -R www-data:www-data /data \
    && a2enmod rewrite

#
## Fixes user permissions for Mac OS [https://github.com/boot2docker/boot2docker/issues/581]
RUN usermod -u 1000 www-data
RUN usermod -G staff www-data

RUN apache2ctl restart || service apache2 restart
